Current
isaf27/groebner_basis pull request #1
Opened 2020-01-03 19:14 UTC by isaf27

some basic classes

2020-01-04 11:28 UTC, DimaTrushin requested changes
Я пока прошелся только над modular.h файлом. Сделал несколько общих замечаний, которые должны быть применимы и к другим файлам. Решил не затягивать и кинуть сразу запрос на изменения, а потом погляжу следующие файлы. В целом читать очень приятно. Есть мелкие copy-paste баги, есть некоторая неряшливость работы с языком. Я постарался обратить на все внимание. Если что не заметил, то я потом еще раз пройдусь по коду. Скорее всего что-то проглядел с первой попытки.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> -#ifndef GROEBNER_BASIS_MODULAR_H
Зря убрал ifndef макросы. В плюсах каждый класс должен быть определен единожды. Если ты include-ами включишь один и тот же header файл несколько раз, то ты несколько раз определишь один и тот же класс. Потому нужны макросы, которые проверяют, что файл уже был включен в единицу трансляции и больше его включать не надо.
- Конкретно в данном случае у тебя идет шаблонн, а не класс, потому это с рук сойдет, но увеличит время компиляции. Однако, гипотетически может быть проблема с какими-нибудь специализвациями шаблона, если ты объявишь их в будущем или специализациями методов.
- Кроме #ifndef можно использовать #pragma once Но я не уверен в кросс-платформенности этого решения. Под Visual Studio точно работает. Думаю и под gcc должно, но я им мало пользовался. Я бы за привычку взял все header-ы обрамлять guard-ами из макросов.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +    private:
Порядок данных в классе:
- public
- protected
- private
Причем в приватных данных сначала метода, потом данные. Данные -- это самое последнее, что должен видеть пользователь класса. У класса самое важное -- интерфейс.
Очень полезно группировать методы вместе по исполняемой роли. Например: в начале фигачим все конструкторы и assignment операторы, арифметические операторы все вместе, логические все вместе и т.д.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +        uint32_t value;
У приватного члена лучше в названии использовать underscore в конце value_, чтобы можно было  отличить от локальных переменных методов и от аргументов методов. Особенно это будет удобно в конструкторе в списке инициализации value_(value) вместо value(value).

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +        modular(uint32_t value = 0) : value(value) {
Когда ты используешь дефолтные параметры конструктора, ты по сути хочешь сэкономить на написании default constructor-а. Предпочтительнее делать так:
public:
 modular() = default;
private:
uint32_t value_ = 0;
То есть ты объявляешь дефолтный конструктор явно (это надо, потому что ты объявил не дефолтный конструктор), а дефолтное значение задаешь присваиванием объекту.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +        modular& operator=(modular copy) {
Убрать assignment operator и copy constructor ниже. Они тебе тут не нужны.
- Во-первых, компилятор за тебя генерирует следующие шесть методов: default constructor, copy constructor, move constructor, copy assignment operator, move assignment operator, destructor.
- Между ними есть некоторые зависимости, в том смысле, что если ты объявляешь какой-то, то часть других методов генерироваться не будет. Например, если ты объявляешь свой собственный деструктор, то copy constructor, move constructor, copy assignment, move assignment не генерируются (что разумно), или если ты объявляешь свой конструктор вида Object(some_other_object), то не генерируется дефолтный конструктор.
- Есть и другие зависимости. Но в твоем случае эти два оператора будут сгенерированы. А то что ты написал -- это и есть их генерация по умолчанию.
- Про неявные методы классов и как они друг от друга зависят очень хорошо рассказано вот тут https://youtu.be/vLinb2fgkHk?t=800 я бы рекомендовал посмотреть все видео целиком.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +}
Новые строки в конце всех файлов! Если гит ругается на это, то это будет мучить всех, кто пользуется твоими файлами через гит.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +            return (*this);
Я бы не ставил скобки вокруг возвращаемого значения просто так. Не могу сейчас вспомнить конкретные примеры, но где-то читал (с примерами), что это меняет семантику поведения кода. Не могу сказать на что это может повлиять конкретно тут и повлияет ли. Но общее правило -- не ставить. Если не забуду и нагуглю, то пришлю ссылку.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +        bool operator==(const modular& other) const {
- Если уж объявляешь оператор равенства, то надо объявить оператор неравенства, причем его имплементация
return !(*this == other);
- Кроме того, разумно операторы объявлять как Inline fiend методы от двух аргументов
friend bool operator==(const modular& first, const modular& second) {
  return first.value_ == second.value_;
}
Причина очень простая. Если у тебя оператор встроенный, то это шаблонный метод класса, потому что у него аргумент modular -- шаблон. А для шаблонных методов не поддерживается конвертация типов. Например нельзя будет написать что-то вроде modular<7>(3) == 3 и уж тем более не сработает 3 == modular<7>(3) потому что первый аргумент не типа modular а типа int.  friend метод позволяет делать конвертацию обоих аргументов.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +        modular operator+(const modular& other) const {
Проблема всех твоих арифметических операций -- у них нет inplace версии. Обычно, когда надо определить операцию сложения делают так:
modular& operator+=(const modular& other) {
 value_ += other.value;
 return *this;
}
friend modular operator+(const modular& first, const modular& second) {
modular result = first;
 result += second;
 return result;
}
То есть ты inplace версию объявляешь явно, а остальные определяешь через нее.
- Вторую версию можно оптимизировать разными путями. В случае данного класса в этом нет особенной необходимости, просто потому что его размер -- uint32_t и нет разницы между копированием и move-ом и RVO не сильно помогает и т.д.  Но для полноты картины напишу.
Простейший подход описан на cppreference https://en.cppreference.com/w/cpp/language/operators в разделе Binary arithmetic operators. Для лево-ассоциативных операций -- это разумный подход.
Второй способ перегрузить все 4 версии с rvalue и lvalue reference в качестве аргументов.
friend modular operator+(const modular&, const modular&);
friend modular operator+(modular&&, const modular&);
friend modular operator+(const modular&, modular&&);
friend modular operator+(modular&&, modular&&);
Это более геморройной, но когда прям позарез надо оптимизировать во что бы то ни стало, то очень полезно. 

- В сухом остатке. Я бы остановился на написании двух версий: inplace и одной friend версии без оптимизаций. Этого должно хватить. Аналогичное замечание по всем другим арифметическим операциям.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +            if (value + other.value >= modulo) {
Кстати, я бы вместо if версии исползовал бы % версию этого алгоритма. Ты можешь просто написать 
value_ = (value_ + other.value_) % modulo;
Гипотетически без условного перехода эта операция выполняется быстрее. Я уже точно не помню количество cpu cycles на каждую операцию (их можно глянуть тут https://www.agner.org/optimize/ в optimization guide), но если память мне не изменяет, то целочисленные операции всегда быстрее любых веток с if-ами.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +            return modular<modulo>((uint64_t)value * (uint64_t)other.value % (uint64_t)modulo);
А я то думал, почему ты uint32_t используешь, а не произвольный целочисленный беззнаковый тип. Оказывается, чтобы не париться с переполнением при умножении. Круто, чо. Очень клевая идея.
Единственное, что мне режет глаз -- c-style cast. В плюсах я привык использовать static_cast<uint64_t>(...). Выглядит более громоздко, но привычнее.
Кроме того, по правилам integral conversion достаточно конвертировать только самое первое значение, остальные конвертируются неявно (хотя правила хорошего тона говорят, что надо проговаривать явно, если не хочешь запутать читателя кода).

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +            return value == other.value;
Copy-paste такой copy-paste. Я потому и говорю, что реализация должна быть 
return !(*this == other);
ибо получаются такие баги, как тут.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +        modular power(uint32_t degree) const {
Я бы предпочел нерекурсивную версию, но пока и так пойдет.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +            assert(((void)"division by zero", value != 0));
Я что-то не могу сообразить зачем тут надо (void) перед текстовым литералом. Поясни, пожалуйста.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +            const auto subpower = this->power(degree / 2);
Плохая тема использовать явное обращение к this внутри метода класса! Это обычно означает, что у тебя дерьмово выбраны имена и тебе надо пояснять, что ты применяешь метод к самому объекту. Здесь проблема в том, что ты пытаешься совместить inplace версию и не inplace версию. Я бы создал два метода:
modular& riseToPower(uint32_t) {
// возводим this в степень
return *this;
}
modular power(uint32_t power) const {
modular result = *this;
result.riseToPower(power);
return result;
}
Тогда в первой версии функции тебе не придется явно указывать this ибо будет понятно, что ты только над ним и работаешь.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +            *this = *this + other;
Это плохой паттерн для Inplace методов. Ты теряешь всю производительность от такой имплементации за счет создания временных объектов при вызове operator+. Лучше реализовывать наоборот, как я указал в комментариях к operator+.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +        bool is_zero() const {
Так как у тебя конструктор monomial(uint32_t) не является explicit, то у тебя возможна конвертация uint32_t к modular. Если сделать operator== friend методом, то можно просто писать modular<7>(3) == 0 без проблем. При этом, так как все шаблонное и будет инлайниться, то скорее всего исполняемый код будет эквивалентен тому, что ты тут напишешь явно. Вообще говоря можно оставить эти методы как есть, но имей в виду, что правильные операторы сравнения эту проблему решают.

2020-01-04 11:28 UTC, DimaTrushin commented on modular.h
> +    template <uint32_t modulo>
Вообще, по-хорошему, тут надо заводить using вида
using ModularValueType = uint32_t;
using ModularValueTypeWithoutOverflow = uint64_t;
и потом пользоваться ими везде далее, чтобы был понятен смысл типов. Не думаю, что конкретно здесь и сейчас надо над этим заморачиваться и это приведет к улучшению кода. Но имей в виду на будущее о подобном дизайне.
Сейчас есть следующие недостатки:
- Просто так ты сильно привязан именно к этой связке типов.
- Если не читать код от начала и до конца, то становится сюрпризом, что при смене типа uint32_t тебе надо поменять еще один вспомогательный тип uint64_t. Это потенциально приводит к багам. Потому подобные зависимости лучше обрамлять в классы из связанных типов. Потому что по сути тебе нужен не один независимый произвольный целочисленный тип, а два: один для работы с типом, другой для гарантии отсутствия overflow и он должен быть в квадрат раз больше исходного типа и только такая пара у тебя будет работать.

2020-01-14 10:18 UTC, DimaTrushin requested changes
Я добавил комментарии к коду мономов.
Есть замечания такие же, как встретились в случае modular. Я часть из них повторил, часть из них умолчал. Предполагается, что все релевантные вещи, ты будешь исправлять и тут.
Основная проблема -- дизайн. Ты хочешь, чтобы количество переменных в мономе было постоянным или переменным? Если постоянным, то плохо использовать std::vector, а если переменным, то не нужен шаблонный параметр. Я это все постарался расписать. Надо принять решение и сделать одно из двух.
Остальные замечания по качеству организации кода и по плюсам.

2020-01-14 10:18 UTC, DimaTrushin commented on modular.h
>          Modular& operator=(Modular copy) {
Кстати, неверная сигнатура оператора. У оператора operator= есть два вида
Modular& operator=(const Modular&);
Modular& operator=(Modular&&) noexcept;
Первый называется copy assignment operator второй -- move assignment operator. Именно эти операторы генерируются автоматически и имеют особую роль.
На сколько я понимаю, так как сигнатура твоего оператора не совпадает с сигнатурой стандартных, они все равно генерировались бы компилятором, если бы не твой собственный copy constructor ниже.
Еще ты делаешь лишнюю копию аргумента. Если уж на то пошло, то надо ниже делать move из аргумента функции, а именно value = std::move(copy.value). Но подобные трюки нужны только для конструкторов.

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +        Monomial() : degree(size, 0) {
Очень дурацкий дизайн.
- Параметр шаблоня является copile-time значением, а размер std::vector является run-time значением. Основной проблемой такого дизайна является возможность изменить размер вектора в run-time и получить рассинхрон с параметром класса size.
- Еще одна тонкость (не беда, а именно тонкость дизайна). Если ты включаешь size в сигнатуру класса, то Monomial<3> и Monomial<4> будут разными типами. То есть для работы с ними в какой-нибудь функции, тебе потребуется генерировать разные версии этой функции с помощью шаблонов. То есть грубо говоря у тебя получаются мономы с зафиксированным во время компиляции максимальным числом переменных. Это может быть то, что ты и хотел, но я просто хочу убедиться.
- Если уж ты хочешь использовать фиксированное число переменных в мономе, то вместо std::vector лучше использовать std::array, так как он гарантирует отсутствие рассинхрона в размере. Однако std::array хранит свои данные по адресу объекта и move операции для него дорогие. Это trade off между локализация данных и тяжелые move-ы, но отсутствие jump-ов в памяти и cache friendly поведение. Если ты хочешь симулировать вектор постоянной длины, то можно использовать std::unique_ptr на std::array.
- Я вообще вот как вижу дизайн мономов. Есть две версии: размер фиксирован в compile-time и размер может меняться в run-time. Первый предназначен для попытки хранить все данные непрерывными массивами. То есть в этом случае у тебя степени мономов лежат в одной области памяти. Ты можешь добавить коэффициент рядом. А в полиноме моном с коэффициентом (то есть терм) хранить в непрерывном массиве или структуре, которая тоже не раскидана по памяти. Тогда гипотетически есть выигрышь от того, что весь полином находится в одной локальной области в памяти и может быть очень сильный буст (вплоть до x200 -- разница в доступе к L1 и к Ram) за счет того, что операции с полиномом не вылазят из кэша. Но у меня никто пока не смог реализовать полиномы по этой схеме. Основная проблема -- поддержка арифметических операций с полиномом, когда он хранится в векторе. То есть там нужны какие-то бинарные деревья поиска на основе вектора, чтобы локальность действительно сработала, но их никто сам писать не хочет. А получилась бы очень крутая версия map.
Другой дизайн -- ты используешь вектор. Тогда ты можешь использовать один единственный тип Monomial для мономов разной длины. Кроме того, для коротких мономов (длины которых меньше size) в векторе ты можешь не хранить лишние элементы. Однако, тогда ты лежишь не локально в памяти и для доступа к памяти нужны разименовывания указателей.
По моему опыту, если первый вариант не реализовать супер аккуратно, то никакого падения производительности во втором подходе по сравнению с первым не наблюдается. Как минимум никто не смог написать нормально первый вариант, чтобы увидеть хоть какое-то его приемущество.

- В сухом остатке. Самый простой способ -- убрать size как шаблонный параметр и сделать возможным хранить степени монома в векторе произвольной длины. Как вариант даже можно воспользоваться std::map если мы хотим хранить разряжено. Тут теоретически еще большая фрагментация данных в памяти идет, но это все тестить надо как будет реально работать.
Другой вариант -- заменить std::vector на std::array и попытаться пойти сложным путем. Время принимать решение.

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +        std::vector<uint32_t> degree;
Как и раньше, приватные данные вниз. У private и protected данных underscore в конце имени, то есть degrees_ вместо degrees. Еще добавь множественное число в название, так как это степени, а не степень. Если хочешь дефолтное значение, то присвой его тут
std::vector<uint32_t> degrees_ = std::vector<uint32_t>(size, 0);

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +        Monomial(std::vector<uint32_t> degree) : degree(degree) {
Конструктор должен делать move из своих аргументов, то есть
Monomial(std::vector<uint32_t> degrees) : degrees_(std::move(degrees)) {}
Но может быть лучше тут сделать инициализация с помощью initializer_list

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +        Monomial(const Monomial &copy) : degree(copy.degree) {
- Во-первых, все конструкторы должны идти в начале public части подряд.
- Во-вторых, если определяешь copy constructor, то желательно определить и move constructor, а так же copy и  move assignment operators.
- В-третьих, у тебя нет custom destructor, все члены класса являются default constractible, copyable, movable, потому тебе нет необходимости определять свои конструкторы и т.д.

Короче, убрать это определение.

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +        Monomial& operator=(Monomial copy) {
- Во-первых, неверная сигнатура для copy assignment оператора.
- Во-вторых, он сгенерируется автоматом, если ты не переопределял copy или move конструкторы или операторы, а так же если нет кастомного деструктора.

Опять же. Убрать.

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +            std::vector<uint32_t> result(size, 0);
Отвратное название. Это не result! Я из-за этого код неправильно прочитал. Результат у тебя моном, а не вектор. Очень путает. tmp_vector в лучшем случае, но никак не result. Но лучше сделать по-другому. Опишу в другом комментарии.

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +            return Monomial<size>(result);
Вот тут происходит лишнее копирование вектора из result внутрь вновь создаваемого монома. Если исправлять по-быстрому, то надо писать
return Monomial<size>(std::move(result));

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +        Monomial operator*(const Monomial& other) const {
Глобально должен быть другой дизайн.
1) Определяешь inplace оператор 
Monomial& operator*=(const Monomial& other);
В нем не надо создавать временные объекты типа result, так как ты все модификации проделываешь над *this.
2) На основе inplace оператора пишешь этот оператор
Monomial operator*(const Monomial& other) {
Monomial result = *this;
result *= other;
return result;
}
При этом автоматически выполнится RVO и result будет создан по адрессу возвращаемого значения. Я кажется про это уже писал в Modular. Но на всякий случай сюда ссылку кину на материалы.
Вот тут можно почитать как оно работает (это актульно для until c++17, но помогает понять, что происходит):
https://www.ibm.com/developerworks/community/blogs/5894415f-be62-4bc0-81c5-3956e82276f3/entry/RVO_V_S_std_move?lang=en
Еще хорошее объяснение есть вот тут
https://stackoverflow.com/questions/12953127/what-are-copy-elision-and-return-value-optimization
и тут
https://stackoverflow.com/questions/38043319/how-does-guaranteed-copy-elision-work
В c++17 во время возврата значения из функции вообще не создается временной переменной:
https://en.cppreference.com/w/cpp/language/copy_elision

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +        bool operator==(const Monomial& other) const {
- Во-первых, в таких случаях всегда надо добавлять оператор неравенства
bool operator!=(const Monomial& other) const {
return !(*this == other);
}
- Во-вторых, лучше все операторы делать friend, так как в этом случае будет конвертация обоих аргументов.

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +        bool operator<(const Monomial& other) const {
Нужны все остальные операторы сравнения и лучше их сделать friend-ами.

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +        bool is_subset(const Monomial& other) const {
Это что еще за метод в интерфейсе монома??? Что значит для монома быть подмножеством?
Я вот тут даже не догадался до того, что ты делаешь, пока в имплементацию не глянул. Это называется is_divisible_by.

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +            assert(((void)"degree should be between 0 and size - 1", (size > num && num >= 0)));
Не верный дизайн. Небезопасный метод в открытом интерфейсе класса. Подумай вот над чем, пусть у тебя есть моном
x^2y^3
и ты спрашиваешь, какая у тебя степень у этого монома по переменной z. Что надо ответить на этот вопрос? Надо сказать 0. А что делаешь ты, ты говоришь "умереть и сказать об этой радостной новости пользователю". Мягко говоря пользователь будет удивлен, что простейшая операция -- "спросить степень", приводит к такому неожиданному результату.
Надо 
return ( num < size ? degrees_[num] : 0);
И еще я бы поменял num на variable_index, это будет лучше отражать смысл происходящего.

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +        friend std::ostream& operator<<(std::ostream &out, const Monomial &element) {
Это можно, нечитая код, сказать, что будет слово "рефакторинг". У тебя 4 вложенных scope друг в друга. Это означает, что у тебя какой-то неправильный дизайн.
- Во-первых, наличие счетчика non_zero_count означает ошибку проектирования. Начнем с его имени, которое вообще ничего не говорит о его цели и для чего ты используешь этот счетчик. Далее, это глобальный счетчик на все тело метода, а в методе есть циклы, вложенные if-ы и еще куча всего, что прямо таки хочет совершить ошибку.
- Во-вторых, как вообще понять логику происходящего? Если во всех других методах достаточно одного взгляда, то тут надо прилагать ментальные усилия, чтобы понять, что ты делаешь.

Основная проблема с вложенными scope в том, что ты не виделил эти scope в отдельные функции, которые бы имели имена. Если функции имеют имена, то они этими именами говорят, что ты делаешь. Как я сейчас вижу, ты делаешь следующее:
1) посчитать количество ненулевых степеней в мономе
2) если их нет, то напечатать 1 и сделать return;
3) иначе сделать цикл по всем ненулевым степеням от первой до предпоследней
 напечатать переменную
 напечатать знак умножения
4) вне цикла напечатать последнюю переменную

В этом случае четко видна структура программы и какие нужны подфункции. На самом деле можно еще сильнее разделить.
1) if моном равен 1, то печать 1 и return
2) иначе вызвать функцию для печати монома с ненулевыми степенями и return

далее приватный метод
функция для печати монома с ненулевыми степенями
assert(что метод вызван правильно и есть ненулевые степени)
1) в цикле от первого до предпоследнего
вызвать функцию печати текущей переменной
печать знака умножения
2) вызвать функцию печати последней переменной

Далее приватный метод
печать переменной

Я ниже пройдусь по коду и напишу, где и что  выделить.

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +            uint32_t non_zero_count = 0;
По-хорошему это пишется так
uint32_t non_zero_degrees_count = get_amount_of_non_zero_degrees();
и код ниже выкинуть в отдельную функцию get_amount_of_non_zero_degrees();
Однако, само количество тебе реально не нужно и ты используешь только наличие ненулевой степени. Смотри комментарии далее к коду.

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +            if (non_zero_count == 0) {
Глобальная структура такая
if (element == 1)
 return out << "1";
else {
 print_non_identical_monomial(out, element);
return out;
}
и все
Далее весь код помещается в функцию print_non_identical_monomial

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +                for (uint32_t i = 0; i < size; ++i) {
Здесь тебе нужен цикл по ненулевым мономам. Я бы нашел позицию последнего ненулевого
uint32_t last_essential_variable_index = element.get_last_essential_variable();
for(uint32_t index = 0; index < last_essential_variable_index; ++index) {
 if(degrees_[index] != 0)
  print_variable(out, element, index);
 out << "*";
}
print_variable(out, element, last_essential_variable_index);

2020-01-14 10:18 UTC, DimaTrushin commented on monomial.h
> +            uint32_t non_zero_count = 0;
Запомни, если у тебя в теле функции есть глобальный счетчик или флаг или еще что-то такое. Это почти всегда ошибка проектирования.

2020-01-14 13:03 UTC, DimaTrushin requested changes
Я набросал еще несколько требований по поводу Polynomial. Я не стал лезть в Ideal класс пока. Там много замечаний аналогичных прошлым и я не везде их указывал. Обрати на это внимание.

2020-01-14 13:03 UTC, DimaTrushin commented on polynomial.h
> +        Polynomial(std::map<Monomial<size>, Field, Compare>&& monomials) : monomials(monomials) {
Такой конструктор по lvalue не сработает. В конструктор всегда передавай объекты по значению.
Единственный случай, когда по значению передавать плохая идея, это когда локальная часть объекта очень большая и move операции являются дорогими. Тогда надо писать две версии оператора: передавать по const Type& и по Type&& (это если Type) имеет тяжелую локальную часть. std::map к таким не относится, если что. Потому удаляй && отсюа и делай monomials_(std::move(monomials)) в списке инициализации.

2020-01-14 13:03 UTC, DimaTrushin commented on polynomial.h
> +        std::map<Monomial<size>, Field, Compare> monomials;
В твоем дизайне явно можно использовать std::array в мономе или std::unique_ptr на std::array. Второй вариант даже предпочтительнее, ибо move будет дешевым. Либо надо все сделать динамическим в run-time и не мучиться с шаблоном size.

2020-01-14 13:03 UTC, DimaTrushin commented on polynomial.h
>                      monomials[element.first] += element.second;
Везде в конструкторах используй std::move, если объект был передан by value.
Кроме того, в конструкторе надо использовать методы для конструирования. У std::map есть метод emplace, которые создает все объекты inplace https://en.cppreference.com/w/cpp/container/map/emplace
Он вставляет пару (ключ, значение), если ключа еще нет и ничего не делает, если ключ есть и умеет сигнализировать об этом флагом. Потому тут надо сделать emplace, проверить вставилось или нет и если не вставилось, то просто доприбваить значение. и везде на element.first и element.second навесить std::move, для правильного выбора нужных move конструкторов.

2020-01-14 13:03 UTC, DimaTrushin commented on polynomial.h
>                  if (!element.second.is_zero()) {
Мы точно хотим предполагать наличие такого метода в интерфейсе поля? Если правильно написаны операторы сравнения, то должна сработать строчка 
if (element.second != 0)
А в релизе за счет inline никаких накладных расходов на этот оператор не будет. Все заинлайнится и будет обычное сравнение начинок элементов поля. В случае Modular будет явно вызывано сравнение двух целых беззнаковых чисел.

2020-01-14 13:03 UTC, DimaTrushin commented on polynomial.h
> +            std::map<Monomial<size>, Field, Compare> result = monomials;
Code duplication. Этот оператор устроен точно так же, как и его inplace версия. Ее надо писать через operator+=. Как я уже объяснял в других комментариях. Это замечание касается всех подобных операторов.

2020-01-14 13:03 UTC, DimaTrushin commented on polynomial.h
> +            if (coefficient.is_zero()) {
Если нужно избавиться от вложенных if else, то можно воспользоваться дополнительными return. Тем более, что компилятор такие вещи лучше умеет оптимизировать. Например
if (coefficient == 0) {
monomials.clear();
return *this;
}
for (auto& monomial : monomials) 
monomial.second *= coefficient;
return *this;

2020-01-14 13:03 UTC, DimaTrushin commented on polynomial.h
> +                    monomials[monomial.first] *= coefficient;
Лишняя работа с доступом к элементу. Можно бежать по ссылке и менять Monomial.second. Я написал в предыдущем комментарии об этом. Но тут хотел еще раз подчеркнуть, чтобы обратить твое внимание.

2020-01-14 13:03 UTC, DimaTrushin commented on polynomial.h
> +        friend std::ostream& operator<<(std::ostream &out, const Polynomial &element) {
Функцию длиной в 23 строчки, даже читать не хочу. Переделать по аналогии с требованиями к Monomial.

2020-01-14 13:03 UTC, DimaTrushin commented on polynomial.h
> +        Monomial<size> get_major_monomial() const {
- Это называется leading monomial, хотя captain monomial или lieutenant monomial тоже не плохо =)
- Еще мне не очень нравится, что мы по значению возвращаем эту штуку. По-хорошему, эта штука должна быть небезопасным методом. Потому что для нулевого многочена нет старшего монома. А значит функция на нем должна либо падать, либо возвращать мусор или что-то еще делать. А на ненулевом многочлене, мы должны вернуть ссылку на старший моном.
- Кроме того, у тебя в случае нулевого многочлена в качестве старшего монома возвращается 1. Что вообще говоря не понятно почему так. Но эту концепцию можно все равно докрутить до возвращения ссылки. Внутри Polynomial заведи статическую переменную IdentityMonomial и возвращай тут константную ссылку на нее, а в случае не нулевого многочлена возвращай то, что возвращаешь.

2020-01-14 13:03 UTC, DimaTrushin commented on polynomial.h
> +                result[element.first * monomial] = element.second;
Я бы тут использовал emplace

2020-01-14 13:03 UTC, DimaTrushin commented on polynomial.h
> +        Polynomial operator*(const Monomial<size>& monomial) const {
Весь этот код надо бы кинуть в operator*=
Там так же создать result (только по нормальному надо его назвать). А потом свапнуть this->monomials_ и result

2020-01-14 13:03 UTC, DimaTrushin commented on polynomial.h
> +        Polynomial operator*(const Polynomial& other) const {
Почему ты никак не используешь уже определенные операторы умножения на коэффициент и на моном?
Ведь тут же просто
Polynomial< ... > result;
for (const auto& term : other.monomials_)
result += *this * term.first * term.second;
Я бы как обычно в начале сделал Inplace версию. В ней надо в конце сделать swap для std::map внутри this и result;

2020-01-14 13:03 UTC, DimaTrushin commented on polynomial.h
> +        std::map<Monomial<size>, Field, Compare> monomials;
Я осознал, что более правильное название -- terms_. Потому что моном -- это только произведение переменных, а коэффициент с мономом -- это терм.

2020-01-14 13:03 UTC, DimaTrushin commented on polynomial.h
> +        bool is_zero() const {
Почему не используется оператор сравнения? У тебя же есть конструктор по коэффициенту. Тогда 
friend bool operator==(const Polynomial&, const Polynomial&);
должен сработать. А за счет inline это будет без накладных расходов.

2020-01-15 18:58 UTC, isaf27 commented on modular.h
> +            assert(((void)"division by zero", value != 0));
error: expression result unused [-Werror,-Wunused-value]

2020-01-16 10:24 UTC, isaf27 commented on modular.h
> +        modular(uint32_t value = 0) : value(value) {
а что делать с тем, что я хочу assert в конструкторе, чтобы всякие плохие значения не появлялись?

2020-01-25 16:56 UTC, DimaTrushin requested changes
Я добавил еще часть замечаний по тому коду, который был изменен.
В целом изменения идут в правильную сторону, но надо еще чуть-чуть отполировать отдельные моменты. Где-то ясть косяки с использованием языка, где-то есть code duplication.
Но самая важная проблема -- дизайн монома. Надо понять, ты хочешь мономы с фиксированным числом переменных или нет? То есть ты хочешь иметь разные классы вида Monomial<2> и Monomial<3> или ты хочешь иметь один класс Monomial, который умеет хранить любое количество переменных. Из-за неопределенности с этим вопросом я не могу продвинуться дальше класса Monomial и что-то содержательное советовать далее.

2020-01-25 16:56 UTC, DimaTrushin commented on modular.h
> +            return *this * other.inverse();
В сложных выражениях можно скобки оставить для повышения читаемости. Я имел в виду только выражения вида
return (что-то);
Нашел текст, в котором объясняется проблема
https://stackoverflow.com/questions/4762662/are-parentheses-around-the-result-significant-in-a-return-statement
Конкретно в твоем случае это не выстреливает, но хорошая практика -- не обрамлять возвращаемое выражение в лишние скобки любого вида.
До c++17 балы еще похожая беда с фигурными скобками , но начиная с c++17 выражения
return {что-то};
return что-то;
работают абсолютно идентично. 
https://stackoverflow.com/questions/45557407/c-this-inside-curly-braces

2020-01-25 16:56 UTC, DimaTrushin commented on modular.h
> +    using ModularValueType64 = uint64_t;
На сколько я понимаю, ты используешь этот тип лишь чтобы избежать overflow в арифметике умножения и от этого типа тебе надо лишь чтобы он был в 2 раза большего размера, чем ModularValueType. Потому разуменее назвать как-нибудь наподобие DoubledModularValueType (или аналогично, но более изящно, сходу не получилось ничего красивого сочинить).
Тут есть еще одна идейная проблема, которая мне не нравится, но на которую я предлагаю забить.  Ты используешь пару глобальных using-ов, которые еще и связаны друг с другом.
- Во-первых, хорошо бы чтобы все using-ги подобные были объявлены внутри тех классов, где они нужны. Но к сожалению Modular использует первый using.
- Во-вторых, второй using является деталью имплементации и потому плохо его иметь глобальным доступным. Однако скрывать его внутри namespace или внутри класса было бы еще хуже, потому что эти два using-га тесно связаны и обязаны располагаться вместе, чтобы при изменениях не забыть поправить оба.
- В-третьих, по-хорошему должен быть helper класс DoublePrecision<T>, который для заданного типа T возвращает аналогичный тип, но с двойной точностью или выдает compile-time error, если для типа T такое сделать нельзя. И тогда вместо объявления второго using-га, в операторе умножения мы используем:
using DoubleType = DoublePrecision<ModualrValueType>;
return Modular<modulo>(
                static_cast < DoubleType >(value_) *
                static_cast < DoubleType >(other.value_) %
                static_cast < DoubleType >(modulo)
            );
Таким образом при смене ModularValueType код либо останется корректно работающим, либо во время компиляции ты получишь ошибку, что вот это последнее место не работает, надо в DoublePrecision добавить имплементацию для нового типа.

2020-01-25 16:56 UTC, DimaTrushin commented on monomial.h
> +    template<MonomialDegreeType size>
Тут несколько проблем с этой строчкой
- Во-первых, у тебя есть два вообще говоря не связанных типа и ты их путаешь между собой: 1) VariableIndexType 2) DegreeType. Вообще говоря никто не запрещает этим двум типам быть разными. Как минимум ты их хочешь отличать визуально, чтобы понимать, где твое число -- это индекс, а где -- степень. Тут похоже должно быть VariableIndexType, а не DegreeType.
- Во-вторых, как я понимаю, ты используешь этот параметр, чтобы задать фиксированное количество переменных в мономе. Потому Monomial< 2 > и Monomial< 3 > это будут разные типы. Однако, в реалзиации Monomial ты хранишь степени в std::vector, который позволяет сделать resize вообще говоря. То есть у Monomial ты хочешь, чтобы количество переменных было compile-time параметром, но у std::vector размер является run-time параметром. Это ошибка дизайна, ты смешиваешь два разных контекста.

Первый вопрос, который ты должен себе задать: ты действительно хочешь иметь мономы с фиксированным числом максимального числа переменных? То есть классы вида Monomial< 2 > или Monomial< 3 > или тебя устроит класс Monomial, который будет иметь любое количество переменных в run-time?

Если ты хочешь оставить std::vector как реализацию, то лучше убрать вообще шаблонный параметр и сделать не шаблонный класс Monomial. Мне казалось, что я об этом уже писал.

2020-01-25 16:56 UTC, DimaTrushin commented on monomial.h
> +    using MonomialDegreeType = uint32_t;
По модулю замечания к шаблону Monomial.
- Во-первых, тут должен быть 
using VariableIndexType = uint32_t;
- Во-вторых, using MonomialDegreeType (как следует из названия класса) является внутренней информацией класса Monomial. Потому вместо глобального using-га здесь, надо внутри класса Monomial объявить public using вида
class Monomial {
...
public:
using DegreeType = uint32_t;
...
};
При этом лишнее Monomial нам не нужно в названии.

2020-01-25 16:56 UTC, DimaTrushin commented on monomial.h
> +        Monomial(std::vector<PolynomialDegreeType> degree) : degree_(degree) {
Потерян std::move
Monomial(std::vector<PolynomialDegreeType> degree) : degree_(std::move(degree)) 
Дело в том, что внутри конструктора переменная degree является lvalue, потому что ей можно присвоить значение (как локальной переменной функции). Потому в строчке
degree_(degree)
вызовется copy constructor для std::vector, что как бы совсем не то, что мы хотим. Тут надо поставить std::move, чтобы переместить содержимое degree в degree_.
Надо не забывать, что конструктор принимает данные by value, но потом ты должен сделать move данных в данные класса.

2020-01-25 16:56 UTC, DimaTrushin commented on polynomial.h
> +        Polynomial(std::map<Monomial<size>, Field, Compare>&& terms) : terms_(terms) {
- Во-первых, потерян move
 terms_(std::move(terms))
- Во-вторых, конструктор сработает только на rvalue std::map, что вряд ли то, что ты хочешь.

Лучше написать так
Polynomial(std::map<Monomial<size>, Field, Compare> terms) : terms_(std::move(terms))
Никаких лишних копий тут НЕ будет.

2020-01-25 16:56 UTC, DimaTrushin commented on modular.h
> +            uint32_t degree = modulo - 2;
заменить uint32_t на ModularValueType

2020-01-25 16:56 UTC, DimaTrushin commented on modular.h
> +            return (first.value_ + second.value_) % modulo;
code duplication
По-хорошему, ты тут пишешь так
Modular result(first);
result += second;
return result;
Так как все методы inline, то по производительности получится то же самое. Будет вообще один и тот же код на уровне ассемблера при использовании ключа -O2 или -O1, а может быть даже без оптимизации.

Убрать везде в подобных случаях повторение кода аналогичным методом во всех классах, а не только в этом.

2020-01-25 16:56 UTC, DimaTrushin commented on monomial.h
> +        Monomial(std::vector<MonomialDegreeType> degree) : degree_(degree) {
Потерян move
Monomial(std::vector<DegreeType> degree) : degree_(std::move(degree))

2020-01-25 16:56 UTC, DimaTrushin commented on monomial.h
> +        friend bool operator<(const Monomial& first, const Monomial& second) {
У тебя получается только один вид сравнения мономов, который (видимо) соответствует лексикографическому порядку. Я вообще говоря планировал другой дизайн. Мономы сами себя сравнивать могут только на равенство и неравенство, а за их порядок должен отвечать отдельный класс сравнения Order. Например в STL есть такие классы как std::less, std::greater_equal и т.д. Задача классов типа Order аналогичная. Потому я бы убрал этот оператор из интерфейса монома.

2020-01-25 16:56 UTC, DimaTrushin commented on monomial.h
> +            for (MonomialDegreeType i = 0; i < size; ++i) {
Подобный код пока не могу комментировать ибо мне до сих пор не понятна политика по поводу параметра size и того, хотим ли мы чтобы количество переменных было параметром класса.

2020-01-25 16:56 UTC, DimaTrushin commented on monomial.h
> +    template<MonomialDegreeType size>
Кстати. чтобы в коде было понятно, что size является шаблонным параметром, и не путать ее с переменными, для шаблонных параметров классов и переменных принято использовать префикс T в начале, то есть Tsize в данном случае.

2020-05-06 19:40 UTC, isaf27 commented
Привет, Дима. Убрал параметр size из Monomial и в целом постарался привести код в порядок. Можешь выделить пожалуйста какие-то основные прям супер злостные нарушения, потому что я честно очень критически посмотрел код и не знаю как к себе придраться.

Еще понял про что ты говорил, когда говорил что авторедукция неправильная, просто потому что сам наткнулся на это. Поэтому сделал 2 вида редукции в Polynomial и Ideal: reduce (редуцировать, только старший член) и full_reduce (редуцировать пока редуцируется хотя бы один член).

2020-06-11 19:53 UTC, merged